### ISSUE TITLE
生成出错，麻烦请教一下该怎么解决

### ISSUE THREAD

**Issue by 5046312** [zhangchen915/material-typecho#1]
Administrator@ITIANKONG MINGW64 ~/Downloads/material-typecho-1.0
$ sh ./build.sh
rm: cannot remove './release/': No such file or directory
cp: cannot stat 'dist': No such file or directory

**Comment by 5046312** [comment]
我是window系统

**Comment by 5046312** [comment]
![image](https://user-images.githubusercontent.com/20859099/43352341-b63489d8-9254-11e8-92f8-3d90c397a54b.png)

**Comment by zhangchen915** [comment]
更新一下代码，重新 `npm i`，再运行 `npm run build`，应该就好了

**Comment by 5046312** [comment]
感谢了，些邪恶

**Comment by 5046312** [comment]
打错，谢谢
